github.com:
    users:
        faynef:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: faynef
